[package]
name = "axis"
version = "0.1.0"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "A radically simple IT automation platform."
homepage = "https://github.com/saturn-xiv/axis"
license = "MIT"
readme = "README.md"

[profile.release]
lto = true

[dependencies]
log = "0.4"
log4rs = "0.8"
toml = "0.5"
failure = "0.1"
nix = "0.15"
base64 = "0.10"
tera = "1.0.0-beta.14"
cursive = "0.12"
git2 = "0.9"
ssh2 = "0.3"
serde = "1"
serde_derive = "1"
serde_json = "1"
clap = "2"

[dependencies.uuid]
version = "0.7"
features = ["v4", "serde"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.diesel]
version = "1"
features = ["sqlite", "chrono"]

[package.metadata.deb]
depends = "$auto, systemd"
section = "admin"
priority = "optional"
maintainer-scripts = "scripts"
assets = [    
    ["assets/log4rs.yml", "etc/axis/", "644"],    
    ["target/release/axis", "usr/bin/", "755"]
]