CREATE TABLE agents(
  id INTEGER PRIMARY KEY NOT NULL,
  sn VARCHAR(255) NOT NULL,
  key VARCHAR(44) NOT NULL, 
  enable BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX idx_agents_sn ON agents(sn);
