[vars]
"job.name" = "Ping"


[[tasks]]
name = 'task 1'
groups = [
    'nano-pi',
    'local',
]
[[tasks.commands]]
type = 'upload'
src = 'jobs/scripts/hi'
dest = '/tmp/hi.sh'

[[tasks.commands]]
type = 'download'
src = '/proc/version'
dest = 'proc/version'

[[tasks.commands]]
type = 'shell'
script = 'jobs/scripts/hi.sh'

[tasks.vars]
"task key 1" = "task val 1"
"task key 2" = "task val "