name = 'ping'
groups = ['web']
hosts = ['localhost', '192.168.8.22']

[vars]
job_description = "Ping-Pong"

[[tasks]]
upload = {local='packages/hi', remote='/tmp/'}
download = {}
shell = {script = "uname -a"}